server:
  port: 9595

spring:
  application:
    name: CLOUD-CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/snehasharma85/config-server
          clone-on-start: true


